// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20211228_IgnitisHomeWork.Data;

namespace _20211228_IgnitisHomeWork.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_20211228_IgnitisHomeWork.Models.CalculationTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CalculationTypeModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2021, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Automatinis"
                        });
                });

            modelBuilder.Entity("_20211228_IgnitisHomeWork.Models.ContractorTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContractorTypeModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2021, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Metinis rangovas"
                        });
                });

            modelBuilder.Entity("_20211228_IgnitisHomeWork.Models.CustomerImportanceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerImportanceModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2021, 12, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = ""
                        });
                });

            modelBuilder.Entity("_20211228_IgnitisHomeWork.Models.RegistrationattributesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CalculationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ContractorTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerImportanceId")
                        .HasColumnType("int");

                    b.Property<bool>("HasContractWork")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBusinessClient")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalculationTypeId");

                    b.HasIndex("ContractorTypeId");

                    b.HasIndex("CustomerImportanceId");

                    b.ToTable("RegistrationattributesModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationTypeId = 1,
                            ContractorTypeId = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerImportanceId = 1,
                            HasContractWork = false,
                            IsBusinessClient = true,
                            IsDeleted = false,
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("_20211228_IgnitisHomeWork.Models.RegistrationattributesModel", b =>
                {
                    b.HasOne("_20211228_IgnitisHomeWork.Models.CalculationTypeModel", "CalculationType")
                        .WithMany("RegistrationAttributes")
                        .HasForeignKey("CalculationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20211228_IgnitisHomeWork.Models.ContractorTypeModel", "ContractorType")
                        .WithMany()
                        .HasForeignKey("ContractorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20211228_IgnitisHomeWork.Models.CustomerImportanceModel", "CustomerImportance")
                        .WithMany()
                        .HasForeignKey("CustomerImportanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculationType");

                    b.Navigation("ContractorType");

                    b.Navigation("CustomerImportance");
                });

            modelBuilder.Entity("_20211228_IgnitisHomeWork.Models.CalculationTypeModel", b =>
                {
                    b.Navigation("RegistrationAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
