// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20211230_IgnitisHomework_V2.Data;

namespace _20211230_IgnitisHomework_V2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220104185821_dataseed")]
    partial class dataseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_20211230_IgnitisHomework_V2.Models.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attribute");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Reikia atlikti rangos darbus"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Rangos darbus atliks"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Verslo klientas"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Skaičiavimo metodas"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Svarbus klientas"
                        });
                });

            modelBuilder.Entity("_20211230_IgnitisHomework_V2.Models.AttributeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.ToTable("AttributeOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeId = 1,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Taip"
                        },
                        new
                        {
                            Id = 2,
                            AttributeId = 1,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Ne"
                        },
                        new
                        {
                            Id = 3,
                            AttributeId = 2,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Metinis rangovas"
                        },
                        new
                        {
                            Id = 4,
                            AttributeId = 3,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Taip"
                        },
                        new
                        {
                            Id = 5,
                            AttributeId = 3,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Ne"
                        },
                        new
                        {
                            Id = 6,
                            AttributeId = 4,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Automatinis"
                        },
                        new
                        {
                            Id = 7,
                            AttributeId = 5,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Taip"
                        },
                        new
                        {
                            Id = 8,
                            AttributeId = 5,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Ne"
                        },
                        new
                        {
                            Id = 9,
                            AttributeId = 5,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = ""
                        });
                });

            modelBuilder.Entity("_20211230_IgnitisHomework_V2.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Registration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("_20211230_IgnitisHomework_V2.Models.RegistrationAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("RegistrationAttribute");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeId = 1,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 1,
                            SelectedOptionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AttributeId = 2,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 1,
                            SelectedOptionId = 3
                        },
                        new
                        {
                            Id = 3,
                            AttributeId = 3,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 1,
                            SelectedOptionId = 5
                        },
                        new
                        {
                            Id = 4,
                            AttributeId = 4,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 1,
                            SelectedOptionId = 6
                        },
                        new
                        {
                            Id = 5,
                            AttributeId = 5,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 1,
                            SelectedOptionId = 7
                        },
                        new
                        {
                            Id = 6,
                            AttributeId = 1,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 2,
                            SelectedOptionId = 1
                        },
                        new
                        {
                            Id = 7,
                            AttributeId = 2,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 2,
                            SelectedOptionId = 3
                        },
                        new
                        {
                            Id = 8,
                            AttributeId = 3,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 2,
                            SelectedOptionId = 5
                        },
                        new
                        {
                            Id = 9,
                            AttributeId = 4,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 2,
                            SelectedOptionId = 6
                        },
                        new
                        {
                            Id = 10,
                            AttributeId = 5,
                            Created = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            LastModified = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            RegistrationId = 2,
                            SelectedOptionId = 7
                        });
                });

            modelBuilder.Entity("_20211230_IgnitisHomework_V2.Models.AttributeOption", b =>
                {
                    b.HasOne("_20211230_IgnitisHomework_V2.Models.Attribute", "Attribute")
                        .WithMany("Options")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("_20211230_IgnitisHomework_V2.Models.RegistrationAttribute", b =>
                {
                    b.HasOne("_20211230_IgnitisHomework_V2.Models.Attribute", "Attribute")
                        .WithMany("RegistrationAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20211230_IgnitisHomework_V2.Models.Registration", "Registration")
                        .WithMany("Attributes")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("_20211230_IgnitisHomework_V2.Models.Attribute", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("RegistrationAttributes");
                });

            modelBuilder.Entity("_20211230_IgnitisHomework_V2.Models.Registration", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
