// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20211215_FirstEFApp.Data;

namespace _20211215_EF_ShopApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211222182514_TagData")]
    partial class TagData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ItemTagModel", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "ShopItemId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("ItemTags");
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 240, DateTimeKind.Utc).AddTicks(3598),
                            ExpiryDate = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Item 1",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 242, DateTimeKind.Utc).AddTicks(2601),
                            ExpiryDate = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Item 2",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 242, DateTimeKind.Utc).AddTicks(2629),
                            ExpiryDate = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Item 3",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 242, DateTimeKind.Utc).AddTicks(2633),
                            ExpiryDate = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Item 4",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 242, DateTimeKind.Utc).AddTicks(2636),
                            ExpiryDate = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Item 5",
                            ShopId = 1
                        });
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 240, DateTimeKind.Utc).AddTicks(3229),
                            IsDeleted = false,
                            Name = "Shop 1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 240, DateTimeKind.Utc).AddTicks(3233),
                            IsDeleted = false,
                            Name = "Shop 2"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 240, DateTimeKind.Utc).AddTicks(3234),
                            IsDeleted = false,
                            Name = "Shop 3"
                        });
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.TagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 239, DateTimeKind.Utc).AddTicks(5537),
                            IsDeleted = false,
                            Name = "Tag 1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 239, DateTimeKind.Utc).AddTicks(6048),
                            IsDeleted = false,
                            Name = "Tag 2"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 12, 22, 18, 25, 14, 239, DateTimeKind.Utc).AddTicks(6051),
                            IsDeleted = false,
                            Name = "Tag 3"
                        });
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ItemTagModel", b =>
                {
                    b.HasOne("_20211215_EF_ShopApp.Models.ShopItemModel", "ShopItem")
                        .WithMany("ItemTags")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20211215_EF_ShopApp.Models.TagModel", "Tag")
                        .WithMany("ItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopItemModel", b =>
                {
                    b.HasOne("_20211215_EF_ShopApp.Models.ShopModel", "Shop")
                        .WithMany("ShopItems")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopItemModel", b =>
                {
                    b.Navigation("ItemTags");
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopModel", b =>
                {
                    b.Navigation("ShopItems");
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.TagModel", b =>
                {
                    b.Navigation("ItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
