// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20211215_FirstEFApp.Data;

namespace _20211215_EF_ShopApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 16, 17, 45, 59, 776, DateTimeKind.Utc).AddTicks(1904),
                            ExpiryDate = new DateTime(2021, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = 0,
                            Name = "Item 1",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 16, 17, 45, 59, 777, DateTimeKind.Utc).AddTicks(8521),
                            ExpiryDate = new DateTime(2021, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = 0,
                            Name = "Item 2",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 12, 16, 17, 45, 59, 777, DateTimeKind.Utc).AddTicks(8550),
                            ExpiryDate = new DateTime(2021, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = 0,
                            Name = "Item 3",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2021, 12, 16, 17, 45, 59, 777, DateTimeKind.Utc).AddTicks(8554),
                            ExpiryDate = new DateTime(2021, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = 0,
                            Name = "Item 4",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2021, 12, 16, 17, 45, 59, 777, DateTimeKind.Utc).AddTicks(8557),
                            ExpiryDate = new DateTime(2021, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = 0,
                            Name = "Item 5",
                            ShopId = 1
                        });
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 16, 17, 45, 59, 775, DateTimeKind.Utc).AddTicks(3091),
                            IsDeleted = 0,
                            Name = "Shop 1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 16, 17, 45, 59, 775, DateTimeKind.Utc).AddTicks(3589),
                            IsDeleted = 0,
                            Name = "Shop 2"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 12, 16, 17, 45, 59, 775, DateTimeKind.Utc).AddTicks(3641),
                            IsDeleted = 0,
                            Name = "Shop 3"
                        });
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopItemModel", b =>
                {
                    b.HasOne("_20211215_EF_ShopApp.Models.ShopModel", "Shop")
                        .WithMany("ShopItems")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("_20211215_EF_ShopApp.Models.ShopModel", b =>
                {
                    b.Navigation("ShopItems");
                });
#pragma warning restore 612, 618
        }
    }
}
